import { UserRole } from "./roles";

export const PERMISSIONS = {
  VIEW_DASHBOARD: "view_dashboard",
  VIEW_ASSETS: "view_assets",
  EDIT_ASSETS: "edit_assets",
  DELETE_ASSETS: "delete_assets",
  APPROVE_TRANSFERS: "approve_transfers",
  MANAGE_USERS: "manage_users",
  MANAGE_MAINTENANCE: "manage_maintenance",
  MANAGE_PROCUREMENT: "manage_procurement",
  VIEW_AUDIT_LOGS: "view_audit_logs",
  MANAGE_CONFIG: "manage_config",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ASSETS,
    PERMISSIONS.EDIT_ASSETS,
    PERMISSIONS.DELETE_ASSETS,
    PERMISSIONS.APPROVE_TRANSFERS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.MANAGE_PROCUREMENT,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_CONFIG,
  ],
  BASE_COMMANDER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ASSETS,
    PERMISSIONS.EDIT_ASSETS,
    PERMISSIONS.APPROVE_TRANSFERS,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  LOGISTICS_OFFICER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ASSETS,
    PERMISSIONS.EDIT_ASSETS,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.MANAGE_PROCUREMENT,
  ],
};
